title: Default Page

columns:
  main:
    width: 2/3
    sections:
      fields:
        type: fields
        fields:
          text:
            type: text
            size: huge
          title:
            label: Title
            type: text
          titleAppend:
            label: Title Append
            type: text
          
          section5_text1:
            label: Section 5 Text 1
            type: text
          section5_text2:
            label: Section 5 Text 2
            type: text
          section5_text3:
            label: Section 5 Text 3
            type: text
  sidebar:
    width: 1/3
    sections:
      pages:
        type: pages
        template: default
      files:
        type: files
